### ISSUE TITLE
run saturn-contracts  inspect-earnings abnormal

### ISSUE THREAD

**Issue by shihuajin111** [filecoin-saturn/contracts#72]
Operating system: ubuntu 22.04

root@ip-172-26-4-202:~# saturn-contracts  inspect-earnings --address  f410fo5mkc6aelpwdgbbqpqghio3mlvcgq2hcrhqsbqq  --factory-address f410fo5mkc6aelpwdgbbqpqghio3mlvcgq2hcrhqsbqq
[*]
 |              _|_|_|              _|
 |              _|          _|_|_|  _|_|_|_|  _|    _|  _|  _|_|  _|_|_|
 |                _|_|    _|    _|    _|      _|    _|  _|_|      _|    _|
 |                    _|  _|    _|    _|      _|    _|  _|        _|    _|
 |              _|_|_|      _|_|_|      _|_|    _|_|_|  _|        _|    _|
 |
 |          -----------------------------------------------------------
 |          Saturn smart contracts 🪐.
 |          -----------------------------------------------------------
 |
[*] current gas price: 761103973
[*] using 10 retries
[*] converting f410fo5mkc6aelpwdgbbqpqghio3mlvcgq2hcrhqsbqq to ETH equivalent
[*] ETH equivalent is 0x7758a178045bec3304307c0c743b6c5d446868e2
[*] converting f410fo5mkc6aelpwdgbbqpqghio3mlvcgq2hcrhqsbqq to ETH equivalent
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AbiError(DecodingError(InvalidName("please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist")))', /root/.cargo/git/checkouts/contracts-f6dccc69c922f7ab/ab65e7e/cli/src/utils.rs:672:73
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f20afcc455bbcc5c0f7679450fb35fd0c9668880/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f20afcc455bbcc5c0f7679450fb35fd0c9668880/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/f20afcc455bbcc5c0f7679450fb35fd0c9668880/library/core/src/result.rs:1651:5
   3: cli::commands::Cli::run::{{closure}}
   4: tokio::runtime::park::CachedParkThread::block_on
   5: tokio::runtime::context::runtime::enter_runtime
   6: tokio::runtime::runtime::Runtime::block_on
   7: saturn_contracts::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by AmeanAsad** [comment]
Hey @shihuajin111 , is this resolved now by using the correct Factory Address for the contract?
